back:
  recording-preference:
    player-custom: true
    default:
      game-play: false
      ender-teleport: false
      portals: false
      death: true
      system: true
      other: false

tpa:
  # Request timeout in seconds
  timeout: 30