back:
  recording-preference:
    player-custom: true
    default:
      game-play: false
      ender-teleport: false
      portals: false
      death: true
      system: true
      other: false

tpa:
  # Request timeout in seconds
  timeout: 30

home:
  max-home-count: 3
  # If enabled, plugin will respect the player meta named 'simpleteleport-home-limit' as a number in Luckperms plugin.
  per-player-limit: false
