name: SimpleTeleport
version: '${version}'
main: io.github.elihuso.simpleteleport.SimpleTeleport
api-version: '1.16'

commands:
  tpa:
    permission: simpleteleport.tpa
  tpcancel:
    permission: simpleteleport.tpcancel
  tpacc:
    permission: simpleteleport.tpacc
    aliases: [tpaccept]
  tpdn:
    permission: simpleteleport.tpdn
    aliases: [tpdeny]
  tprandom:
    permission: simpleteleport.tprandom
    aliases: [tpr]
  tp2p:
    permission: simpleteleport.tp2p
  🍥:
    permission: simpleteleport.🍥
  tppos:
    permission: simpleteleport.tppos
    aliases: [tpxyz, tpposition]
  spawn:
    permission: simpleteleport.spawn

permissions:
  simpleteleport.tpa:
    default: true
  simpleteleport.tpcancel:
    default: true
  simpleteleport.tpacc:
    default: true
  simpleteleport.tpdn:
    default: true
  simpleteleport.tprandom:
    default: false
  simpleteleport.tp2p:
    default: false
  simpleteleport.🍥:
    default: true
  simpleteleport.tppos:
    default: false
  simpleteleport.spawn:
    default: true