name: SimpleTeleport
version: '${version}'
main: io.github.elihuso.simpleteleport.SimpleTeleport
api-version: '1.16'

commands:
  tpa:
    permission: simpleteleport.tpa
  tpcancel:
    permission: simpleteleport.tpcancel
  tpacc:
    permission: simpleteleport.tpacc
  tpdn:
    permission: simpleteleport.tpdn

permissions:
  simpleteleport.tpa:
    default: true
  simpleteleport.tpcancel:
    default: true
  simpleteleport.tpacc:
    default: true
  simpleteleport.tpdn:
    default: true
